export enum CharacterCategory {
    Gojuuon,
    Dakuon,
    Handakuon,
    Youon,
    Sokuon,
    Foreign,
}

export type KanaContent = {
    romaji: string;
    katakana: string;
    hiragana: string;
    category: CharacterCategory;
};

const content: KanaContent[] = [
    {
        romaji: "a",
        katakana: "ア",
        hiragana: "あ",
        category: CharacterCategory.Gojuuon,
    },
    {
        romaji: "i",
        katakana: "イ",
        hiragana: "い",
        category: CharacterCategory.Gojuuon,
    },
    {
        romaji: "u",
        katakana: "ウ",
        hiragana: "う",
        category: CharacterCategory.Gojuuon,
    },
    {
        romaji: "e",
        katakana: "エ",
        hiragana: "え",
        category: CharacterCategory.Gojuuon,
    },
    {
        romaji: "o",
        katakana: "オ",
        hiragana: "お",
        category: CharacterCategory.Gojuuon,
    },
    {
        romaji: "ka",
        katakana: "カ",
        hiragana: "か",
        category: CharacterCategory.Gojuuon,
    },
    {
        romaji: "ki",
        katakana: "キ",
        hiragana: "き",
        category: CharacterCategory.Gojuuon,
    },
    {
        romaji: "ku",
        katakana: "ク",
        hiragana: "く",
        category: CharacterCategory.Gojuuon,
    },
    {
        romaji: "ke",
        katakana: "ケ",
        hiragana: "け",
        category: CharacterCategory.Gojuuon,
    },
    {
        romaji: "ko",
        katakana: "コ",
        hiragana: "こ",
        category: CharacterCategory.Gojuuon,
    },
    {
        romaji: "sa",
        katakana: "サ",
        hiragana: "さ",
        category: CharacterCategory.Gojuuon,
    },
    {
        romaji: "shi",
        katakana: "シ",
        hiragana: "し",
        category: CharacterCategory.Gojuuon,
    },
    {
        romaji: "su",
        katakana: "ス",
        hiragana: "す",
        category: CharacterCategory.Gojuuon,
    },
    {
        romaji: "se",
        katakana: "セ",
        hiragana: "せ",
        category: CharacterCategory.Gojuuon,
    },
    {
        romaji: "so",
        katakana: "ソ",
        hiragana: "そ",
        category: CharacterCategory.Gojuuon,
    },
    {
        romaji: "ta",
        katakana: "タ",
        hiragana: "た",
        category: CharacterCategory.Gojuuon,
    },
    {
        romaji: "chi",
        katakana: "チ",
        hiragana: "ち",
        category: CharacterCategory.Gojuuon,
    },
    {
        romaji: "tsu",
        katakana: "ツ",
        hiragana: "つ",
        category: CharacterCategory.Gojuuon,
    },
    {
        romaji: "te",
        katakana: "テ",
        hiragana: "て",
        category: CharacterCategory.Gojuuon,
    },
    {
        romaji: "to",
        katakana: "ト",
        hiragana: "と",
        category: CharacterCategory.Gojuuon,
    },
    {
        romaji: "na",
        katakana: "ナ",
        hiragana: "な",
        category: CharacterCategory.Gojuuon,
    },
    {
        romaji: "ni",
        katakana: "ニ",
        hiragana: "に",
        category: CharacterCategory.Gojuuon,
    },
    {
        romaji: "nu",
        katakana: "ヌ",
        hiragana: "ぬ",
        category: CharacterCategory.Gojuuon,
    },
    {
        romaji: "ne",
        katakana: "ネ",
        hiragana: "ね",
        category: CharacterCategory.Gojuuon,
    },
    {
        romaji: "no",
        katakana: "ノ",
        hiragana: "の",
        category: CharacterCategory.Gojuuon,
    },
    {
        romaji: "ha",
        katakana: "ハ",
        hiragana: "は",
        category: CharacterCategory.Gojuuon,
    },
    {
        romaji: "hi",
        katakana: "ヒ",
        hiragana: "ひ",
        category: CharacterCategory.Gojuuon,
    },
    {
        romaji: "fu",
        katakana: "フ",
        hiragana: "ふ",
        category: CharacterCategory.Gojuuon,
    },
    {
        romaji: "he",
        katakana: "へ",
        hiragana: "ヘ",
        category: CharacterCategory.Gojuuon,
    },
    {
        romaji: "ho",
        katakana: "ホ",
        hiragana: "ほ",
        category: CharacterCategory.Gojuuon,
    },
    {
        romaji: "ma",
        katakana: "マ",
        hiragana: "ま",
        category: CharacterCategory.Gojuuon,
    },
    {
        romaji: "mi",
        katakana: "ミ",
        hiragana: "み",
        category: CharacterCategory.Gojuuon,
    },
    {
        romaji: "mu",
        katakana: "ム",
        hiragana: "む",
        category: CharacterCategory.Gojuuon,
    },
    {
        romaji: "me",
        katakana: "メ",
        hiragana: "め",
        category: CharacterCategory.Gojuuon,
    },
    {
        romaji: "mo",
        katakana: "モ",
        hiragana: "も",
        category: CharacterCategory.Gojuuon,
    },
    {
        romaji: "ya",
        katakana: "ヤ",
        hiragana: "や",
        category: CharacterCategory.Gojuuon,
    },
    {
        romaji: "yu",
        katakana: "ユ",
        hiragana: "ゆ",
        category: CharacterCategory.Gojuuon,
    },
    {
        romaji: "yo",
        katakana: "ヨ",
        hiragana: "よ",
        category: CharacterCategory.Gojuuon,
    },
    {
        romaji: "ra",
        katakana: "ラ",
        hiragana: "ら",
        category: CharacterCategory.Gojuuon,
    },
    {
        romaji: "ri",
        katakana: "リ",
        hiragana: "り",
        category: CharacterCategory.Gojuuon,
    },
    {
        romaji: "ru",
        katakana: "ル",
        hiragana: "る",
        category: CharacterCategory.Gojuuon,
    },
    {
        romaji: "re",
        katakana: "レ",
        hiragana: "れ",
        category: CharacterCategory.Gojuuon,
    },
    {
        romaji: "ro",
        katakana: "ロ",
        hiragana: "ろ",
        category: CharacterCategory.Gojuuon,
    },
    {
        romaji: "wa",
        katakana: "ワ",
        hiragana: "わ",
        category: CharacterCategory.Gojuuon,
    },
    {
        romaji: "(w)o",
        katakana: "ヲ",
        hiragana: "を",
        category: CharacterCategory.Gojuuon,
    },
    {
        romaji: "n",
        katakana: "ン",
        hiragana: "ん",
        category: CharacterCategory.Gojuuon,
    },
    {
        romaji: "ga",
        katakana: "ガ",
        hiragana: "が",
        category: CharacterCategory.Dakuon,
    },
    {
        romaji: "gi",
        katakana: "ギ",
        hiragana: "ぎ",
        category: CharacterCategory.Dakuon,
    },
    {
        romaji: "gu",
        katakana: "グ",
        hiragana: "ぐ",
        category: CharacterCategory.Dakuon,
    },
    {
        romaji: "ge",
        katakana: "ゲ",
        hiragana: "げ",
        category: CharacterCategory.Dakuon,
    },
    {
        romaji: "go",
        katakana: "ゴ",
        hiragana: "ご",
        category: CharacterCategory.Dakuon,
    },
    {
        romaji: "za",
        katakana: "ザ",
        hiragana: "ざ",
        category: CharacterCategory.Dakuon,
    },
    {
        romaji: "ji",
        katakana: "ジ",
        hiragana: "じ",
        category: CharacterCategory.Dakuon,
    },
    {
        romaji: "zu",
        katakana: "ズ",
        hiragana: "ず",
        category: CharacterCategory.Dakuon,
    },
    {
        romaji: "ze",
        katakana: "ゼ",
        hiragana: "ぜ",
        category: CharacterCategory.Dakuon,
    },
    {
        romaji: "zo",
        katakana: "ゾ",
        hiragana: "ぞ",
        category: CharacterCategory.Dakuon,
    },
    {
        romaji: "da",
        katakana: "ダ",
        hiragana: "だ",
        category: CharacterCategory.Dakuon,
    },
    {
        romaji: "ji",
        katakana: "ヂ",
        hiragana: "ぢ",
        category: CharacterCategory.Dakuon,
    },
    {
        romaji: "dzu",
        katakana: "ヅ",
        hiragana: "づ",
        category: CharacterCategory.Dakuon,
    },
    {
        romaji: "de",
        katakana: "デ",
        hiragana: "で",
        category: CharacterCategory.Dakuon,
    },
    {
        romaji: "do",
        katakana: "ド",
        hiragana: "ど",
        category: CharacterCategory.Dakuon,
    },
    {
        romaji: "ba",
        katakana: "バ",
        hiragana: "ば",
        category: CharacterCategory.Dakuon,
    },
    {
        romaji: "bi",
        katakana: "ビ",
        hiragana: "び",
        category: CharacterCategory.Dakuon,
    },
    {
        romaji: "bu",
        katakana: "ブ",
        hiragana: "ぶ",
        category: CharacterCategory.Dakuon,
    },
    {
        romaji: "be",
        katakana: "べ",
        hiragana: "べ",
        category: CharacterCategory.Dakuon,
    },
    {
        romaji: "bo",
        katakana: "ボ",
        hiragana: "ぼ",
        category: CharacterCategory.Dakuon,
    },
    {
        romaji: "pa",
        katakana: "パ",
        hiragana: "ぱ",
        category: CharacterCategory.Handakuon,
    },
    {
        romaji: "pi",
        katakana: "ピ",
        hiragana: "ぴ",
        category: CharacterCategory.Handakuon,
    },
    {
        romaji: "pu",
        katakana: "プ",
        hiragana: "ぷ",
        category: CharacterCategory.Handakuon,
    },
    {
        romaji: "pe",
        katakana: "ぺ",
        hiragana: "ぺ",
        category: CharacterCategory.Handakuon,
    },
    {
        romaji: "po",
        katakana: "ポ",
        hiragana: "ぽ",
        category: CharacterCategory.Handakuon,
    },
    {
        romaji: "kya",
        katakana: "キャ",
        hiragana: "きゃ",
        category: CharacterCategory.Youon,
    },
    {
        romaji: "kyu",
        katakana: "キュ",
        hiragana: "きゅ",
        category: CharacterCategory.Youon,
    },
    {
        romaji: "kyo",
        katakana: "キョ",
        hiragana: "きょ",
        category: CharacterCategory.Youon,
    },
    {
        romaji: "sha",
        katakana: "シャ",
        hiragana: "しゃ",
        category: CharacterCategory.Youon,
    },
    {
        romaji: "shu",
        katakana: "シュ",
        hiragana: "しゅ",
        category: CharacterCategory.Youon,
    },
    {
        romaji: "she",
        katakana: "シェ",
        hiragana: "しぇ",
        category: CharacterCategory.Youon,
    },
    {
        romaji: "sho",
        katakana: "ショ",
        hiragana: "しょ",
        category: CharacterCategory.Youon,
    },
    {
        romaji: "cha",
        katakana: "チャ",
        hiragana: "ちゃ",
        category: CharacterCategory.Youon,
    },
    {
        romaji: "chu",
        katakana: "チュ",
        hiragana: "ちゅ",
        category: CharacterCategory.Youon,
    },
    {
        romaji: "che",
        katakana: "チェ",
        hiragana: "ちぇ",
        category: CharacterCategory.Youon,
    },
    {
        romaji: "cho",
        katakana: "チョ",
        hiragana: "ちょ",
        category: CharacterCategory.Youon,
    },
    {
        romaji: "nya",
        katakana: "ニャ",
        hiragana: "にゃ",
        category: CharacterCategory.Youon,
    },
    {
        romaji: "nyu",
        katakana: "ニュ",
        hiragana: "にゅ",
        category: CharacterCategory.Youon,
    },
    {
        romaji: "nyo",
        katakana: "ニョ",
        hiragana: "にょ",
        category: CharacterCategory.Youon,
    },
    {
        romaji: "hya",
        katakana: "ヒャ",
        hiragana: "ひゃ",
        category: CharacterCategory.Youon,
    },
    {
        romaji: "hyu",
        katakana: "ヒュ",
        hiragana: "ひゅ",
        category: CharacterCategory.Youon,
    },
    {
        romaji: "hyo",
        katakana: "ヒョ",
        hiragana: "ひょ",
        category: CharacterCategory.Youon,
    },
    {
        romaji: "mya",
        katakana: "ミャ",
        hiragana: "みゃ",
        category: CharacterCategory.Youon,
    },
    {
        romaji: "myu",
        katakana: "ミュ",
        hiragana: "みゅ",
        category: CharacterCategory.Youon,
    },
    {
        romaji: "myo",
        katakana: "ミョ",
        hiragana: "みょ",
        category: CharacterCategory.Youon,
    },
    {
        romaji: "rya",
        katakana: "リャ",
        hiragana: "りゃ",
        category: CharacterCategory.Youon,
    },
    {
        romaji: "ryu",
        katakana: "リュ",
        hiragana: "りゅ",
        category: CharacterCategory.Youon,
    },
    {
        romaji: "ryo",
        katakana: "リョ",
        hiragana: "りょ",
        category: CharacterCategory.Youon,
    },
    {
        romaji: "gya",
        katakana: "ギャ",
        hiragana: "ぎゃ",
        category: CharacterCategory.Youon,
    },
    {
        romaji: "gyu",
        katakana: "ギュ",
        hiragana: "ぎゅ",
        category: CharacterCategory.Youon,
    },
    {
        romaji: "gyo",
        katakana: "ギョ",
        hiragana: "ぎょ",
        category: CharacterCategory.Youon,
    },
    {
        romaji: "ja",
        katakana: "ジャ",
        hiragana: "じゃ",
        category: CharacterCategory.Youon,
    },
    {
        romaji: "je",
        katakana: "ジェ",
        hiragana: "じぇ",
        category: CharacterCategory.Youon,
    },
    {
        romaji: "ju",
        katakana: "ジュ",
        hiragana: "じゅ",
        category: CharacterCategory.Youon,
    },
    {
        romaji: "jo",
        katakana: "ジョ",
        hiragana: "じょ",
        category: CharacterCategory.Youon,
    },
    {
        romaji: "bya",
        katakana: "ビャ",
        hiragana: "びゃ",
        category: CharacterCategory.Youon,
    },
    {
        romaji: "byu",
        katakana: "ビュ",
        hiragana: "びゅ",
        category: CharacterCategory.Youon,
    },
    {
        romaji: "byo",
        katakana: "ビョ",
        hiragana: "びょ",
        category: CharacterCategory.Youon,
    },
    {
        romaji: "pya",
        katakana: "ピャ",
        hiragana: "ぴゃ",
        category: CharacterCategory.Youon,
    },
    {
        romaji: "pyu",
        katakana: "ピュ",
        hiragana: "ぴゅ",
        category: CharacterCategory.Youon,
    },
    {
        romaji: "pyo",
        katakana: "ピョ",
        hiragana: "ぴょ",
        category: CharacterCategory.Youon,
    },
    {
        romaji: "`double consonant`",
        katakana: "ッ",
        hiragana: "っ",
        category: CharacterCategory.Sokuon,
    },
    {
        romaji: "wi",
        katakana: "ウィ",
        hiragana: "うぃ",
        category: CharacterCategory.Foreign,
    },
    {
        romaji: "we",
        katakana: "ウェ",
        hiragana: "うぇ",
        category: CharacterCategory.Foreign,
    },
    {
        romaji: "wo",
        katakana: "ウォ",
        hiragana: "うぉ",
        category: CharacterCategory.Foreign,
    },
    {
        romaji: "tsa",
        katakana: "ツァ",
        hiragana: "つぁ",
        category: CharacterCategory.Foreign,
    },
    {
        romaji: "tsi",
        katakana: "ツィ",
        hiragana: "つぃ",
        category: CharacterCategory.Foreign,
    },
    {
        romaji: "tse",
        katakana: "ツェ",
        hiragana: "つぇ",
        category: CharacterCategory.Foreign,
    },
    {
        romaji: "tso",
        katakana: "ツォ",
        hiragana: "つぉ",
        category: CharacterCategory.Foreign,
    },
    {
        romaji: "ti",
        katakana: "ティ",
        hiragana: "てぃ",
        category: CharacterCategory.Foreign,
    },
    {
        romaji: "fa",
        katakana: "ファ",
        hiragana: "ふぁ",
        category: CharacterCategory.Foreign,
    },
    {
        romaji: "fi",
        katakana: "フィ",
        hiragana: "ふぃ",
        category: CharacterCategory.Foreign,
    },
    {
        romaji: "fyu",
        katakana: "フュ",
        hiragana: "ふゅ",
        category: CharacterCategory.Foreign,
    },
    {
        romaji: "fe",
        katakana: "フェ",
        hiragana: "ふぇ",
        category: CharacterCategory.Foreign,
    },
    {
        romaji: "fo",
        katakana: "フォ",
        hiragana: "ふぉ",
        category: CharacterCategory.Foreign,
    },
    {
        romaji: "di",
        katakana: "ディ",
        hiragana: "でぃ",
        category: CharacterCategory.Foreign,
    },
    {
        romaji: "dyu",
        katakana: "デュ",
        hiragana: "でゅ",
        category: CharacterCategory.Foreign,
    },
    {
        romaji: "va",
        katakana: "ヴァ",
        hiragana: "ゔぁ",
        category: CharacterCategory.Foreign,
    },
    {
        romaji: "vi",
        katakana: "ヴィ",
        hiragana: "ゔぃ",
        category: CharacterCategory.Foreign,
    },
    {
        romaji: "vu",
        katakana: "ヴ",
        hiragana: "ゔ",
        category: CharacterCategory.Foreign,
    },
    {
        romaji: "ve",
        katakana: "ヴェ",
        hiragana: "ゔぇ",
        category: CharacterCategory.Foreign,
    },
    {
        romaji: "vo",
        katakana: "ヴォ",
        hiragana: "ゔぉ",
        category: CharacterCategory.Foreign,
    },
];

export default content;
